### ISSUE TITLE
[Bug]: Pipeline Runs Scheduled & Triggered Table Width Issues

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the Pipeline Runs Schedule table is between 1200 and 1300 pixels it runs off the right side of the page.

Not sure what is up with it -- possible columns not properly sizing? The Runs Triggered table does not have this issue -- same number of columns. 

Best guess is it might be the Toggle component doing something to spacing for the row.

[Update] When the Pipeline name exceeds a certain length, it causes the Pipeline run table under the Triggered tab to become unresponsive and stretch beyond the right side of the screen. Upon initially entering this tab, I couldn't access the table's kebab menu and the full pagination view.

### Expected Behavior

The table should size and columns should wrap as needed. No running off the side of the page.

### Steps To Reproduce

1. Have a project
2. Install the Pipelines Server (depending on when we handle this -- that could be requiring a valid Data Connection to AWS S3)
3. Create a Pipeline with long name, like  `long pipeline nameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` 
4. Create a Run that is scheduled or Triggered(specify the start, end or frequency of the run)
5. View the Global Pipeline Runs page

### Workaround (if any)

Wider or smaller screen

### Open Data Hub Version

```yml
Unreleased at this time
Dashboard: v2.10.0
```

### Anything else

Might get to this while the feature is on-going (in `f/pipelines), but likely will be after it merges into `main`.

**Comment by andrewballantyne** [comment]
I can't reproduce this -- may have been fixed by another issue.

**Comment by dpanshug** [comment]
Reopening the issue, as the bug still exist when we have long Pipeline name.

When the Pipeline name exceeds a certain length, it causes the Pipeline run table under the `Triggered` tab to become unresponsive and stretch beyond the right side of the screen. Upon initially entering this tab, I couldn't access the table's kebab menu and the full pagination view. 

Please refer to the attached screenshot. 
![Screenshot from 2023-09-01 13-23-05](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/42f73bef-ed31-4551-bac6-a97d48d96705)

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1790
